[package]
name = "axum-askama-todo-app"
version = "0.1.0"
edition = "2024"

[dependencies]
askama = "0.16.1"
axum = { version = "0.8.9", features = ["macros"] }
regex = "1.13.1"
serde = { version = "1.0.229", features = ["derive"] }
tokio = { version = "1.53.1", features = ["full"] }
tower-http = { version = "0.7.1", features = ["fs", "trace"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
validator = { version = "0.21.0", features = ["derive"] }
